# Generated by Django 6.0.4 on 2026-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_capacity_event_description_attendee_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('event', 'email')},
        ),
    ]
